lista = input().split(' ')
p1 = int(lista[0])
q1 = int(lista[1])
v1 = float(lista[2])
lista2 = input().split(' ')
p2 = int(lista2[0])
q2 = int(lista2[1])
v2 = float(lista2[2])
valortotal = (q1*v1)+(q2*v2)
print('VALOR A PAGAR: R$ {:.2f}'.format(valortotal))
